In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

np1=np.array([1,2,3,4])

np2=np.array((5,6,7,8))

print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [7]:
np3=np.arange(0,31,2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [8]:
np4=np.linspace(1,15,3)
print(np4)

[ 1.  8. 15.]


In [9]:
np5=np.zeros((5,))
print(np5)

[0. 0. 0. 0. 0.]


In [10]:
np6=np.ones((5,))
print(np6)

[1. 1. 1. 1. 1.]


In [11]:
np7=np.ones((5,2))
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
listdata=[[1,2,3,4,5],[6,7,8,9,10]]

np8=np.array(listdata)
print(np8)
print('維度', np8.ndim)
print('形狀', np8.shape)
print('數量', np8.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
維度 2
形狀 (2, 5)
數量 10


In [14]:
np9=np.arange(1,21)
print(np9)

np10=np9.reshape(4,5)
print(np10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
np10=np.arange(0,9)

print(np10)

[0 1 2 3 4 5 6 7 8]


In [16]:
print(np10[0])

0


In [17]:
print(np10[8])

8


In [18]:
print(np10[1:8])

[1 2 3 4 5 6 7]


In [19]:
print(np10[1:8:2])

[1 3 5 7]


In [20]:
print(np10[8:1:-1])

[8 7 6 5 4 3 2]


In [21]:
print(np10[:])

[0 1 2 3 4 5 6 7 8]


In [22]:
print(np10[:4])

[0 1 2 3]


In [23]:
print(np10[4:])

[4 5 6 7 8]


In [24]:
np11 = np.arange(1, 21).reshape(5, 4)
np11
np11[0,2]
np11[1, 2]
print(np11[1:3, 2])
print(np11[1:3, 1:3])
print(np11[::2, ::2])
print(np11[:,2])
print(np11[1,:])
print(np11[:, :])

[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]
 [17 19]]
[ 3  7 11 15 19]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [26]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)
print(np12.shape)
np12

(30, 4)


array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [27]:
print ('1.產生2x3 0~1之間的隨機浮點數\n',  np.random.rand(2,3))

1.產生2x3 0~1之間的隨機浮點數
 [[0.26629049 0.54726164 0.40778144]
 [0.27548847 0.72590736 0.50045634]]


In [28]:
print('2.產生2×3常態分布的隨機浮點數\n', np.random.randn(2,3))

2.產生2×3常態分布的隨機浮點數
 [[ 2.17939921 -0.40655092 -1.4387848 ]
 [-1.55891136  0.06926751 -0.22484976]]


In [29]:
print('3.產生0~4(不含5)隨機整數(75)\n',np.random.randint(5))

3.產生0~4(不含5)隨機整數(75)
 0


In [30]:
print('4.產生2~4(不含5)5個隨機整數\n', np.random.randint(2,5,[5]))

4.產生2~4(不含5)5個隨機整數
 [2 4 3 2 2]


In [31]:
print('5.產生3個 0~1之間的隨機浮點數\n',np.random.random(3), '\n',
np.random.random_sample(3), '\n',
np.random.sample(3))

5.產生3個 0~1之間的隨機浮點數
 [0.32928182 0.75403947 0.81033516] 
 [0.94354724 0.16272977 0.4846906 ] 
 [0.67858786 0.49861085 0.75008561]
